INSERT INTO Drones(ID, PRECIO, COLOR, DE) VALUES (1, 1000, 'negro', 'HOVERAir X1');
INSERT INTO Drones(ID, PRECIO, COLOR, DE) VALUES (2, 1500, 'rojo', 'H4DRC F11 PRO');
INSERT INTO Drones(ID, PRECIO, COLOR, DE) VALUES (3, 2000, 'azul', 'CASC CH-92');
