INSERT INTO Drones(ID, NAME, APELLIDO, DE) VALUES (1, 'Paco', 'Gonzalez', 'HOVERAir X1');
INSERT INTO Drones(ID, NAME, APELLIDO, DE) VALUES (2, 'Mario', 'Garcia', 'H4DRC F11 PRO');
INSERT INTO Drones(ID, NAME, APELLIDO, DE) VALUES (3, 'Carlos', 'Lopez', 'CASC CH-92');
